- name: Assert required vars are defined
  ansible.builtin.assert:
    that:
      - host_dest_file_path is defined
      - host_dest_mode is defined
      - host_dest_owner is defined
      - host_dest_group is defined
      - source_volume_name is defined
      - backup_container_name is defined
      - backup_image is defined
      - backup_container_source_dir_path is defined
      - backup_container_dest_dir_path is defined
      - local_dest_file_path is defined
      - auto_remove is defined

- name: Set the filename (basename) of the host_dest_file_path
  set_fact:
    _host_dest_filename: "{{ host_dest_file_path | basename }}"

- name: Set full backup_container_dest_file_path
  set_fact:
    _backup_container_dest_file_path: "{{ backup_container_dest_dir_path + '/' + _host_dest_filename }}"

- name: Set the default command
  set_fact:
    _default_backup_container_command: '/bin/sh -c "tar -cvzf {{ _backup_container_dest_file_path }} -C {{ backup_container_source_dir_path }} ."'

- name: Echo the backup command
  ansible.builtin.debug:
    msg: "{{ backup_container_command | default(_default_backup_container_command) }}"

- name: Create the backup container
  ansible.builtin.docker_container:
    name: "{{ backup_container_name }}"
    image: "{{ backup_image }}"
    volumes:
      - "{{ source_volume_name }}:{{ backup_container_source_dir_path }}"
      - "{{ host_dest_file_path | dirname }}:{{ backup_container_dest_dir_path }}"
    command: "{{ backup_container_command | default(_default_backup_container_command) }}"
    # Cannot detach because we need to block and wait for the backup to complete
    detach: no
    state: started
    restart_policy: no
    auto_remove: "{{ auto_remove }}"
    keep_volumes: no

- name: Copy file from the remote host to local
  ansible.builtin.fetch:
    src: "{{ host_dest_file_path }}"
    dest: "{{ local_dest_file_path }}"
    flat: yes
    fail_on_missing: yes
    validate_checksum: yes
    checksum_algorithm: sha256
