all:
  vars:
    ansible_user: ansible
  hosts:
    9c9b38653dae4f4ebbd120adba40ac33:
      ansible_host: 192.168.0.28
      docker_volume_backups:
        - source_volume_name: codekaizen_website_wordpress_db_data
          host_dest_path: "/tmp/docker_volume_backup_{{ ansible_date_time.iso8601_micro | to_uuid }}"
          local_dest_path: "/tmp"
